### ISSUE TITLE
Issue in BiometricAuthentication

### ISSUE THREAD

**Issue by nikichanko** [rushisangani/BiometricAuthentication#12]
Hi,
thx for this pod it is very useful.
I tested on Xcode 9.2 and swift version 4.0.
I found error in public func faceIDAvailable().
I think it might be like this:

public func faceIDAvailable() -> Bool {
        if #available(iOS 11.0, *) {
            let context = LAContext()
            return (context.canEvaluatePolicy(LAPolicy.deviceOwnerAuthenticationWithBiometrics, error: nil) && context.biometryType == LABiometryType.faceID)
        }
        return false
    }

**Comment by rushisangani** [comment]
Hi @nikichanko, could you please describe your error more?
Because it's working in all cases.

**LABiometryType. faceID** or . **faceID** doesn't make any difference.

**Comment by Mahan3340** [comment]
same here , compile error , swift 4 , latest version of  Xcode , line 86 
Binary operator '==' cannot be applied to operands of type 'LABiometryType' and '_'

**Comment by Mahan3340** [comment]
I fixed it by unlocking the file and then replacing it with .faceID

**Comment by rushisangani** [comment]
@Mahan3340 & @nikichanko please update to your pod to the latest version **BiometricAuthentication (1.0.4)**

Thanks for the support :)

**Comment by dotnetguy83** [comment]
Hi. Thanks for your code.
Could I ask a kind of different issue?
I want to check 'the devices' supporting FaceID. (after all iPhone X)
context.biometryType is None, When an iPhone X has no passcode & no FaceID.
Is there a way not only to check current users LocalAuthentication Policy but a device supporting FaceID?

**Comment by rushisangani** [comment]
I guess there is no way to check if the device supports face id or not if device does not set passcode or face id using LAContext API.

For that we can do something like below:
1. create an array containing face id devices:
`let faceIdDevices = ["iPhonex"]`  // in future we need to add more device manually.

2. check current device's frame
3. If it's size is equal to iPhone X size then only we can identify that device supports face id.
4. In future, we need to do some extra work to add more devices in the array.

**Comment by rushisangani** [comment]
For me, If you get biometryType = None, simply do not do anything, just handle the app without biometric authentication.

**Comment by dotnetguy83** [comment]
@rushisangani My Apps Login View UI & Error Messages depend on biometryType. Your answer no.1 is my choice. Thanks a lot in advance.
