### ISSUE TITLE
What About Older devices

### ISSUE THREAD

**Issue by ErAshu** [rushisangani/BiometricAuthentication#13]
Hi Rushi,
Thanks for the lib.
I don't have the device which is not supported touchId like (iPhone 4s, iPhone 5). 
Is this case handle in this library ?

**Comment by rushisangani** [comment]
@ErAshu, this is not handled as of now, I'll add it to the next version.
Thanks

**Comment by rushisangani** [comment]
issue resolved in version 1.0.5
