### ISSUE TITLE
Any chance you can help change the BioAuthenticator.swift so it can be used by existing Objective C project?

### ISSUE THREAD

**Issue by billylo1** [rushisangani/BiometricAuthentication#14]
It seems that Objective C is having trouble importing the public methods (if I add the @objc attribute to it).  The success function block and failure function block is not compatible with Objective C.

thanks,

`BioMetricAuthenticator.swift:52:203: Function types cannot be represented in Objective-C unless their parameters and returns can be`

```
    /// Check for biometric authentication
    public class func authenticateWithBioMetrics(reason: String, fallbackTitle: String? = "", cancelTitle: String? = "", success successBlock:@escaping AuthenticationSuccess, failure failureBlock:@escaping AuthenticationFailure)
```

**Comment by rushisangani** [comment]
@billylo1, as of now you can create a new swift class inherited from NSObject and use the pod from that file.
ex.

```
@objc class Authenticator: NSObject {
    
    // MARK: - Singleton
    static let shared = Authenticator()
    
    func peformAuthentication() {
        
        BioMetricAuthenticator.authenticateWithBioMetrics(reason: "", success: {
            
            // authentication successful
            
        }, failure: { [weak self] (error) in
            
            // failed
        })
    }
}
```

and calling from objective c file:` [[Authenticator shared] peformAuthentication];`
