### ISSUE TITLE
How Can I Get Fingerprint Data

### ISSUE THREAD

**Issue by hatimmakki** [rushisangani/BiometricAuthentication#16]
Hi
I am trying to save fingerprint data or hash into a local db.
Can I do that with this library?

thanks

**Comment by rushisangani** [comment]
We can not any fingerprint or biometric data from the device. This is restricted by the Apple.
Btw, why do you need that?

**Comment by hatimmakki** [comment]
@rushisangani I need it to secure an app with fingerprint pin code. Means, a pin code but instead of using numbers, it uses fingerprints
