### ISSUE TITLE
Demo cannot run with new key

### ISSUE THREAD

**Issue by robcecil** [rushisangani/BiometricAuthentication#19]
"This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSFaceIDUsageDescription key with a string value explaining to the user how the app uses this data."

The Demo app's info.plist just needs this key.

**Comment by rushisangani** [comment]
@robcecil this is resolved in the latest version of BiometricAuthentication 1.0.6.
