### ISSUE TITLE
BiometicAuthentication Xcode 10 beta 1 compile error.

### ISSUE THREAD

**Issue by johnlietzke** [rushisangani/BiometricAuthentication#20]
BioMetricAuthenticator.swift

let errorType = AuthenticationError(error: err as! LAError)
has error:
'AuthenticationError' cannot be constructed because it has no accessible initializers

**Comment by rushisangani** [comment]
@johnlietzke Thanks for the update :)

This can be resolved by: **AuthenticationError.init(error: err as! LAError)**
Please let me know if you found any other issue.

Thanks again.

**Comment by ColdGrub1384** [comment]
@rushisangani That didn't resolved the issue for me. I had to write <pre>AuthenticationError.&#x60;init&#x60;(error: err as! LAError)</pre>

**Comment by nealsun** [comment]
why declare init function like this 
```
public static func `init`(error: LAError) -> AuthenticationError`
```
 I think this is better `public init(error: LAError)`
I modify the init function:
```
public init(error: LAError) {
        switch Int32(error.errorCode) {
            
        case kLAErrorAuthenticationFailed:
            self = .failed
        case kLAErrorUserCancel:
            self = .canceledByUser
        case kLAErrorUserFallback:
            self = .fallback
        case kLAErrorSystemCancel:
            self = .canceledBySystem
        case kLAErrorPasscodeNotSet:
            self = .passcodeNotSet
        case kLAErrorBiometryNotAvailable:
            self = .biometryNotAvailable
        case kLAErrorBiometryNotEnrolled:
            self = .biometryNotEnrolled
        case kLAErrorBiometryLockout:
            self = .biometryLockedout
        default:
           self = .other
        }
    }
```
It works Xcode 10 beta

**Comment by johnlietzke** [comment]
Rushi,

Thanks for the reply.  I will run pod update.

Best,
John

**Comment by ColdGrub1384** [comment]
@johnlietzke yes that’s better

**Comment by ColdGrub1384** [comment]
@nealsun Yes, that’s better

**Comment by rushisangani** [comment]
@nealsun Upto XCode 9.3 we can not declare custom init function without ``. I guess this is removed from latest XCode version.

**Comment by rushisangani** [comment]
@nealsun @johnlietzke @ColdGrub1384 
This has been resolved in latest version of **BiometricAuthentication (2.0).**

Method name renamed to `initWithError(_ error: LAError)` to avoid build error for both new and old xcode versions.

**Comment by johnlietzke** [comment]
Thanks Rashi,

The update works perfectly.
