### ISSUE TITLE
touchIDAvailable()

### ISSUE THREAD

**Issue by gintechsystems** [rushisangani/BiometricAuthentication#22]
Hello,

I think it would be useful to be able to see if touch id is available for devices that may not support the option or I believe if the device has touch id but is turned off, LAContext returns false. It would basically be a copy of faceIDAvailable() function just swapped with touchID biometric type. If you need me to create a pull request I can help out.

Thanks
Joe

**Comment by rushisangani** [comment]
@gintechsystems 
It would be great if you can add that touchIDAvailable function, to make it more useful.

Thanks

**Comment by gintechsystems** [comment]
@rushisangani I will implement this when I can, thank you.

**Comment by rushisangani** [comment]
Please upgrade to the latest version **2.1**
