### ISSUE TITLE
❌  /TeamCity/buildAgentCheckin/work/52fc722467427422/TaskManager/TaskManager/Login/Coordinators/AuthenticationCoordinator.swift:11:8: no such module 'BiometricAuthentication'

### ISSUE THREAD

**Issue by mbdhack** [rushisangani/BiometricAuthentication#23]
I have changed the provisioning profile in my  Xcode and try to build my project in team city and this error pops ups 

Here is the complete log 
Testing failed:
	No such module 'BiometricAuthentication'
	Command CompileSwift failed with a nonzero exit code
	Testing cancelled because the build failed.
** TEST FAILED **

**Comment by rushisangani** [comment]
@mbdhack can you please describe your error with more details.
Like -> XCode version, iOS version, Cocoapods or Carthage version, Swift version?
Is this happening for one project or every project?
