### ISSUE TITLE
TouchID 'remembered' even with allowableReuseDuration = 0

### ISSUE THREAD

**Issue by fvvliet** [rushisangani/BiometricAuthentication#26]
Hello BiometricAuthentication users,

I use this nice SDK in an iOS project (XCode 10.1, Swift 4). Even when I set allowableReuseDuration = 0, the touchID is remembered by the device and not requested again. Any idea what could be the cause of this ?

Thanks for any advice
Frank

**Comment by rushisangani** [comment]
@fvvliet 
I would suggest you to not set 'allowableReuseDuration = 0' at all, if you do not want to reuse the authentication.

**Comment by fvvliet** [comment]
When I left out this setting the result was the same: the touchID kept remembered for x seconds and could only be cleared by closing the app and remove it from memory.
So I need a solution to change this behaviour...

**Comment by rushisangani** [comment]
@fvvliet I need to check this issue.
Till then may be you can set 1 second 'allowableReuseDuration = 1' to make it work properly.

I will surely get back to you.
Thanks.

**Comment by fvvliet** [comment]
@rushisangani
You were right, don't set the allowableReuseDuration at all. Then an LAContext is created every time and there is no reuse of the touchID.

Thanks for your advice !
Frank

**Comment by rushisangani** [comment]
Cool!
