### ISSUE TITLE
Cannot import BiometricAuthentication

### ISSUE THREAD

**Issue by sariminapp** [rushisangani/BiometricAuthentication#27]
I use latest version of BiometricAuthentication (2.2), after pod install.
When I try to import BiometricAuthentication, it cannot show snippet.
When I add manually import BiometricAuthentication, it has crash on modulemap and some private func.

Please repair this.
I use Xcode 10.1 and swift 4.2

**Comment by rushisangani** [comment]
@sariminapp I just created a new project and install the pod BiometricAuthentication (2.2)
I am able to import the pod and use it properly.

Could you please share what issues you are facing or try updating cocoa pods and then reinstall.

**Comment by sariminapp** [comment]
@rushisangani 
I try with latest 2.2.1. Now the problem disappear.
Thanks. You can closed this issue.
