### ISSUE TITLE
Do you support Swift 4?

### ISSUE THREAD

**Issue by zhouhao27** [rushisangani/BiometricAuthentication#29]
Got the following error message:

`/Authentication/BioMetricAuthenticator.swift:70:138: Use of undeclared type 'Result'`

Do you have code for Swift 4?

**Comment by rushisangani** [comment]
@zhouhao27 thanks for using this library.

You can install the older version of this library with swift 4.
`pod 'BiometricAuthentication', '~> 2.2'`

**Comment by rushisangani** [comment]
@zhouhao27 Did that work?

**Comment by zhouhao27** [comment]
Yes. It works. Thanks.

Actually I'm seeking some fingerprint recognition solution because Apple's solution doesn't allow to save user id with its corresponding fingerprint.
