### ISSUE TITLE
Undeclared type Result error prompt

### ISSUE THREAD

**Issue by arishanapalli** [rushisangani/BiometricAuthentication#31]
Use of undeclared type 'Result'

`    class func authenticateWithBioMetrics(reason: String, fallbackTitle: String? = "", cancelTitle: String? = "", completion: @escaping (Result<Bool, AuthenticationError>) -> Void) {
`
from class BioMetricAuthenticator

**Comment by kay14** [comment]
@arishanapalli What version of Xcode are you running. The "Result" enum was introduced in Swift 5 and it requires Xcode 10.2+.

**Comment by arishanapalli** [comment]
I am using Swift 4.2 not Swift 5,  I have restriction for using Swift 5.
So currently using  Xcode Version 10.1 (10B61) & swift 4.2
What will be the alternative to use Result into lower version Swift 4.2 it will be helpfull.

**Comment by kiran4991** [comment]
@arishanapalli did you find any solution. I am also facing the same issue

**Comment by rushisangani** [comment]
@arishanapalli I will have a look, to make it compatible with Swift4. The problem is I have integrated new improvements in Swift5, and I have to make it in Swift4 as well.
Meanwhile, why can't you convert your project to Swift5?

**Comment by kiran4991** [comment]
I have restriction for using Swift 5.

**Comment by rushisangani** [comment]
@kiran4991 @arishanapalli I think you both can use version 2.1.
[2.1](https://github.com/rushisangani/BiometricAuthentication/releases/tag/2.1)
Specify the tag in your pod file, and let me know if that works for you.
