### ISSUE TITLE
Framework not compatible for iOS-13 [Enhancement]

### ISSUE THREAD

**Issue by akshardarji** [rushisangani/BiometricAuthentication#33]
While building the application in Xcode 11-beta, we are facing the following issue by the compiler: 

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

Can you please check and try to resolve so that we can fix it in our project as well. 

Framework with Swift version: [5.0.1]
Xcode version: [11.0 beta-2]
Your application language: [Swift-5.1]

**Comment by rushisangani** [comment]
@akshardarji can you try with following link:
https://stackoverflow.com/questions/46726077/module-compiled-with-swift-4-0-cannot-be-imported-in-swift-4-0-1

Are you using cocoapods or carthage?

**Comment by akshardarji** [comment]
@rushisangani Thanks for your quick response. 

We are using your framework directly as it was required some customization in error messages.

**Comment by akshardarji** [comment]
@rushisangani Thanks for your assistance. It's fixed for me. 
The solution worked when we have updated your `Swift-5.1` framework from your build product into our project.
