### ISSUE TITLE
What does the project add to LocalAuthentication framework API?

### ISSUE THREAD

**Issue by rayx** [rushisangani/BiometricAuthentication#36]
May I ask what are the project's additional features compared to the built-in `LocalAuthentication` framework? I read the usage section in readme and tried the example, but it's still not clear to me. BTW, when trying the example, I notice that the project doesn't support device passcode by default (I believe it can be customized because there is a section in readme discussing fallback title). In my opinion, that's more like a limitation because if user doesn't enable touch/face id, it's better off to just use passcode rather than ask user to enable touch/face if for the app.

Background: I'm adding user authentication support to my app. I read `LocalAuthentication` doc and find it's simple to use. During the course I also find this project, which I believe is a wrapper of `LocalAuthentication`. But it's not clear to me what are the additional features the project provide. I think it may help to list them in readme for people to evaluate the project. Just my thought. Thanks.

**Comment by rushisangani** [comment]
@rayx Thanks for the feedback.

- The whole idea to introduce `LocalAuthentication` is to use Biometric Authentication (not the passcode one). So as per your suggestion for adding default option to authenticate with the passcode defeats the purpose. Instead, user should be encouraged to use FaceId or TouchId for secure and faster authentication.

This library provides following features:
- Easy to use by single method call
- Better handling of FaceID and TouchID authentication, and Error scenarios.
- Easy to check if device supports FaceId or TouchId authentication.
- Asks for Passcode Authentication automatically after several failed attempts.

No wonder, you can always use standard approach and frameworks provided by the Apple. However any public library always has a wrapper around the standard frameworks for ease of use and maybe better handling like this one.

Hope this helps. :)

**Comment by rayx** [comment]
@rushisangani Thanks for your reply.

>     * The whole idea to introduce `LocalAuthentication` is to use Biometric Authentication (not the passcode one). So as per your suggestion for adding default option to authenticate with the passcode defeats the purpose. Instead, user should be encouraged to use FaceId or TouchId for secure and faster authentication.

I see your point, though I still think it's a bit aggresive for an app (not a system security app) to ask user to do a system-wide change. Given that it's rare that iPhone user don't enable touch/face id, the two decisions might not have big difference in practice. I guess there must be a portion of code in the project that deals with the situation where user doesn't enable biometric authentication (e.g., guiding user to enable), but the built-in `LocalAuthentication` framework just falls over to authenticate user with device passcode.

> This library provides following features:
>     * Easy to use by single method call
>     * Better handling of FaceID and TouchID authentication, and Error scenarios.
>     * Easy to check if device supports FaceId or TouchId authentication.
>     * Asks for Passcode Authentication automatically after several failed attempts.

I believe what you said (there must be a reason for the project's high star counts). It's just that, given `LocalAuthentication` framework is so simple to use, I can't see the reason why not use it directly. If I understand what you said correctly, it may be more accurate to think the project *use* `LocalAuthentication` rather than *wrap* it. They have different goals: `LocalAuthentication`supports all authentication approach, but the project focuses on biometric authentication. It just happens that project has similar interface as `LocalAuthentication`.

I think I'll use the built-in framework and may re-evaluate the project when I have different requirement in future. I'm closing the issue. Thanks.
