### ISSUE TITLE
Authenticate view appears on other screens such as notification

### ISSUE THREAD

**Issue by anz6490** [rushisangani/BiometricAuthentication#37]
I set a timer of 5 min to logout the app and shows loginViewConroller. In view will appear I call the Authenticate method.

But the problem is if the user is not on app screen and reading notification. When timer triggers and authenticate view appears on top of Notification screen.

**Comment by rushisangani** [comment]
@anz6490 I believe, this is not the library issue. You have to manage according to the application requirement.
