### ISSUE TITLE
Message: This app was designed to support Touch ID. It has not been updated for Face ID

### ISSUE THREAD

**Issue by daviddelmonte** [rushisangani/BiometricAuthentication#4]
I'm getting this message. How do I fix it please

**Comment by rushisangani** [comment]
Could you please tell me which are steps you're doing? or some code that you've implemented.

- Your app must specify permissions in info.plist for FaceID.
- For Touch ID does not require any permission.

**Comment by daviddelmonte** [comment]
Thank you.. "Your app must specify permissions in info.plist for FaceID" was the issue!

**Comment by adititiwari225** [comment]
Why it is always shows popup with title "Confirm your face to authentication", even i used only touchID for authentication.

**Comment by rushisangani** [comment]
@adititiwari225  Could you please share your code?
So that I can debug more on that.
