### ISSUE TITLE
Binary operator '==' cannot be applied to operands of type 'LABiometryType' and '_'

### ISSUE THREAD

**Issue by janninho** [rushisangani/BiometricAuthentication#8]
`public func faceIDAvailable() -> Bool {
        if #available(iOS 11.0, *) {
            let context = LAContext()
            return (context.canEvaluatePolicy(LAPolicy.deviceOwnerAuthenticationWithBiometrics, error: nil) && context.biometryType == .typeFaceID)
        }
        return false
    }`

returns an error

**Comment by janninho** [comment]
fixed by:

`public func faceIDAvailable() -> Bool {
        if #available(iOS 11.0, *) {
            let context = LAContext()
            return (context.canEvaluatePolicy(LAPolicy.deviceOwnerAuthenticationWithBiometrics, error: nil) && context.biometryType == **.faceID**)
        }
        return false
    }`

**Comment by rushisangani** [comment]
It's working on Xcode 9.1, iOS 11, Swift 3.2 and Swift 4.0.
Could you please mention Xcode, iOS and Swift version that you're using.

**Comment by zjfjack** [comment]
He was using Xcode 9.2, looks like some keywords changed. Fixed this issue through(.typeFaceID -> .faceID, .typeTouchID -> .touchID)
